### PR TITLE
fix: add Json annotation in Prohibition class

### LINKED ISSUE #2117: Missing JsonPropertyName in Prohibition Class
# Bug Report
While I was going through the Policy Code of the EDC I saw that the JsonPropertyName in
the class Prohibition is missing, is it not required or just missing? - see picture:

image

Greetings and thanks in advance!

### PR DESCRIPTION
**Pull request by mukta2022**
## What this PR changes/adds

Add @jsontypeName and @Jsondeserialization in Prohibition class

## Why it does that

Change prohibiton class

## Linked Issue(s)

Closes #2117

### CODE REVIEW

**Review by jimmarino — APPROVED** [review]

**Review by jimmarino — COMMENTED** [review]
Can you add a test for this please?

**Comment by mukta2022** [comment]
> Can you add a test for this please?

Can you kindly tell me little details, what test you mean?

**Comment by jimmarino** [comment]
> > Can you add a test for this please?
> 
> Hello Jim, do you mean, a ProhibitionTest class to add? or anything else? kindly explain a bit please.

A serialization/deserialization test. There are examples from other model classes.

**Comment by mukta2022** [comment]
> A serialization/deserialization test



> > > Can you add a test for this please?
> > 
> > 
> > Hello Jim, do you mean, a ProhibitionTest class to add? or anything else? kindly explain a bit please.
> 
> A serialization/deserialization test. There are examples from other model classes.

Good morning. Thanks , i will have a look on it

**Pull request closed without merging**
