### PR TITLE
refactor(headers): fix checkstyle on headers and configure error for header check

### LINKED ISSUE #2322: Fix checkstyle warnings on headers
# Feature Request

Some files contains bad formatted header

## Which Areas Would Be Affected?
build

## Why Is the Feature Desired?
remove checkstyle warning

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

Fixes all checkstyle warning on file headers

## Why it does that

Consistency in file headers and less warning when building and in the IDE

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes #2322 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

**Review by jimmarino — COMMENTED** [review]
I saw some of the license headers remove 2020-2022 and replace it with 2022. The original start date should remain. Can you change those?

**Comment by wolf4ood** [comment]
Those were actually wrong because the file where created in 2022. 
Probably it' was my fault in previous PR with my configuration

**Review by jimmarino — APPROVED** [review]

**Review by paullatzelsperger — COMMENTED** [review]
Shouldn't we update the checkstyle regex, rather than changing the time range of the copyright?

**Comment by wolf4ood** [comment]
I guess the regex is fine, since it checks the range `from - to` but since there was no blocker i was able to sneak wrong range `from-to` cause i had the wrong settings in Intellij. But for those files the modified in this PR the correct year is `2022`

**Review by ndr-brt — APPROVED** [review]

**Pull request merged**
