### PR TITLE
docs: add decision record about state machine manual interactions

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Adds a decision record about state machine manual interactions

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Part of #3308 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

**Review by jimmarino — APPROVED** [review]
I have two wording nits:

1. Can we call hook `TransitionGuard` or just `Guard` since it is a bit more descriptive?
2. instead of `setWaitingForManualInteraction` can we name it `setWaitingOnGuard` or a more generic term? This mechanism could be used for things other than manual interaction.

Otherwise LGTM.

**Comment by ndr-brt** [comment]
> I have two wording nits:
> 
> 1. Can we call hook `TransitionGuard` or just `Guard` since it is a bit more descriptive?
> 2. instead of `setWaitingForManualInteraction` can we name it `setWaitingOnGuard` or a more generic term? This mechanism could be used for things other than manual interaction.
> 
> Otherwise LGTM.

I agree on the `Guard` term, actually I like it more than hook.

Talking about the manual interaction, that's only a particular kind of guard that will only serve that precise scope, so in the entity I would still talking about "manual interaction" or something that reminds that.

**Comment by jimmarino** [comment]
> > I have two wording nits:
> > 
> > 1. Can we call hook `TransitionGuard` or just `Guard` since it is a bit more descriptive?
> > 2. instead of `setWaitingForManualInteraction` can we name it `setWaitingOnGuard` or a more generic term? This mechanism could be used for things other than manual interaction.
> > 
> > Otherwise LGTM.
> 
> I agree on the `Guard` term, actually I like it more than hook.
> 
> Talking about the manual interaction, that's only a particular kind of guard that will only serve that precise scope, so in the entity I would still talking about "manual interaction" or something that reminds that.

Would "external interaction" work? I'm looking for a more general term since it could be an external system that transitions the sm and not necessarily a manual interaction.

**Comment by ndr-brt** [comment]
> > > I have two wording nits:
> > > 
> > > 1. Can we call hook `TransitionGuard` or just `Guard` since it is a bit more descriptive?
> > > 2. instead of `setWaitingForManualInteraction` can we name it `setWaitingOnGuard` or a more generic term? This mechanism could be used for things other than manual interaction.
> > > 
> > > Otherwise LGTM.
> > 
> > 
> > I agree on the `Guard` term, actually I like it more than hook.
> > Talking about the manual interaction, that's only a particular kind of guard that will only serve that precise scope, so in the entity I would still talking about "manual interaction" or something that reminds that.
> 
> Would "external interaction" work? I'm looking for a more general term since it could be an external system that transitions the sm and not necessarily a manual interaction.

Good point, I'd say yes, also, it could also be called just "waiting", or "pending", like, a "pending contract negotiation" is a negotiation that's waiting for an external interaction, and having a simple term to call it will make everything easier to understand. what do you think?

**Pull request merged**
