### PR TITLE
refactor: add issue date to ids messages

### PR DESCRIPTION
**Pull request by juliapampus**
## What this PR changes/adds

Adds `issued` property to IDS messages.

## Why it does that

The calender de/serialization issue has been resolved some weeks ago.

## Further notes

--
## Linked Issue(s)

Relates #1600 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Review by ndr-brt — APPROVED** [review]
Just a comment not directly related to this PR, I think the `CalendarUtil.gregorianNow` should use the `Clock` service, as it is the one responsible for creating dates and timestamps

**Comment by juliapampus** [comment]
> Just a comment not directly related to this PR, I think the `CalendarUtil.gregorianNow` should use the `Clock` service, as it is the one responsible for creating dates and timestamps

@ronjaquensel commented that it would be nice to have the test todos removed. Do you have an idea about what pattern could be working to match the format of `"2022-07-14T13:01:06.842+02:00"`? Played around a little bit and this "+02:00" seems to make problems although, using an online tool, some expressions worked for this string.

**Comment by juliapampus** [comment]
> @ronjaquensel commented that it would be nice to have the test todos removed. Do you have an idea about what pattern could be working to match the format of `"2022-07-14T13:01:06.842+02:00"`? Played around a little bit and this "+02:00" seems to make problems although, using an online tool, some expressions worked for this string. @ndr-brt

nvm, got it working this second... :D

**Comment by ndr-brt** [comment]
@juliapampus @ronjaquensel I would avoid regex as much as possible, in this case we can rely on the java datetime formatters:
```java
jsonHeader.inPath("$.ids:issued").isString().satisfies(date -> {
    assertThat(DateTimeFormatter.ISO_OFFSET_DATE_TIME.parse(date)).isNotNull();
});
```

**Review by ronjaquensel — APPROVED** [review]

**Pull request merged**
