### PR TITLE
Feature/multi idenitity

### PR DESCRIPTION
**Pull request by michinger**
## What this PR changes/adds

_Briefly describe WHAT your pr changes, which features it adds/modifies._

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

**Comment by paullatzelsperger** [comment]
@michinger you violate _every_ contribution rule we have. Please discuss your idea first (in discussions), outlining clearly what you plan to do and why you think it's necessary. then, once it has gotten traction and is approved by the commiters, raise an issue, further detailing the implementation. 
Only then can a PR be raised. PRs must be described properly, too.

Frankly, looking very briefly over the code, I see little chance that this would ever get accepted.

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
@michinger you violate _every_ contribution rule we have. Please discuss your idea first (in discussions), outlining clearly what you plan to do and why you think it's necessary. then, once it has gotten traction and is approved by the commiters, raise an issue, further detailing the implementation. 
Only then can a PR be raised. PRs must be described properly, too.

Frankly, looking very briefly over the code, I see little chance that this would ever get accepted. I recommend you close this PR, go back and familiarize yourself with our contribution guidelines and etiquette as well as our architectural principles and code guidelines, and then start over again.

**Comment by jimmarino** [comment]
To follow-up on @paullatzelsperger said, both DSP and EDC explicitly pin a participant agent to a single identity. There is nothing stopping you from deploying multiple participant agents in a single process. However, adding the ability for an EDC *instance* to multiplex between identities will not be accepted.

I'm going to close this PR because it has no chance of being merged.

**Comment by michinger** [comment]
Sorry for the premature PR creation, I was unaware it was creating a PR on the eclipse-edc/Connector repository, my intention was to create it on our forked repo. I am aware this is highly experimental and not all ready to be reviewed.

**Pull request closed without merging**
