### PR TITLE
feat: dataspace protocol negotiation dispatcher

### PR DESCRIPTION
**Pull request by juliapampus**
## What this PR changes/adds

Adds delegates for dsp negotiation messages.

## Why it does that

Implement dataspace protocol

## Further notes

Adds dependencies:
- `:data-protocols:dsp:dsp-negotiation:dsp-negotiation-spi`
- `:data-protocols:dsp:dsp-negotiation:dsp-negotiation-transform` (classes are contributed with #2771)

## Linked Issue(s)

Relates #2474

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

**Review by jimmarino — COMMENTED** [review]
Couldn't some of the boilerplate code around creating a JSON structure, HTTP request and dispatching it be pulled up into an abstract class?

**Comment by juliapampus** [comment]
> Couldn't some of the boilerplate code around creating a JSON structure, HTTP request and dispatching it be pulled up into an abstract class?

Agree. When you are okay with it, I would open an issue for this refactoring. I guess we could also merge this with the transformer dispatchers and add the abstract class to the `dsp-http-core` module.

**Comment by jimmarino** [comment]
I think we should refactor this PR to include the abstract class because it will simplify the code, which contains a lot of duplication. Later we can move the abstract class out in a subsequent PR.

**Review by ndr-brt — COMMENTED** [review]
> Couldn't some of the boilerplate code around creating a JSON structure, HTTP request and dispatching it be pulled up into an abstract class?

I would prefer a collaborator, its behavior is pretty clear, serialize a `RemoteMessage`, it could be an interface called `RemoteMessageSerializer` with the `JsonLdRemoteMessageSerializer` implementation.

I agree that this should be done in this PR, it won't take much and it will simplify tests a lot

**Comment by juliapampus** [comment]
PR is rebased. @ronjaquensel will take care of refactoring. The refactored structure will then also be used in #2760.

**Comment by ronjaquensel** [comment]
@ndr-brt @jimmarino I refactored the delegates as follows:

* Introcuded `JsonLdRemoteMessageSerializer` interface and implementation in `dsp-http-spi` and `dsp-http-core` respectively (for now, can be moved further up when required). This serializer is now used by the delegates to transform, compact and serialize a message.
* Made `DspHttpDispatcherDelegate` an abstract class and moved the code for creating the HTTP request there. As this is specific to HTTP dispatchers, I think it makes more sense in the abstract class than as an additional helper class. But as this is just a single method, it should not make the code harder to read/understand.
* Introduced a `testFixture` for delegates, as pretty much the same code was duplicated between many of the delegate tests. The `testFixture` itself does not contain `@Test` annotated methods, but instead provides methods for testing the common behaviour that can be used in the delegate tests. First, I wanted to move the actual tests to the `testFixture` class, but as the delegate tests use these methods in different combinations (e.g. some parse the response body, others don't), that quickly became rather confusing and unreadable.

**Review by jimmarino — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]

**Pull request merged**
