### PR TITLE
Konfiguration und Implementierung des Connectors(Lokale Ausführung un…

### PR DESCRIPTION
**Pull request by Thierry1405**
…d Ausführung mit Docke Image) sowie erstellen von paar Dateien für Testzwecken.

### CODE REVIEW

**Comment by jimmarino** [comment]
Thanks for the contribution, but what is the purpose of this PR?

**Comment by Thierry1405** [comment]
> Thanks for the contribution, but what is the purpose of this PR?

Hallo I'm working on the project for my bachelor's thesis and i wanted to make a commit and push on my repository and i think that is an error . should i delete the PR ?

**Comment by jimmarino** [comment]
OK good luck!

**Comment by florianrusch-zf** [comment]
Hey @Thierry1405 can I ask you what your bachelor thesis is about?

**Comment by Thierry1405** [comment]
> Hey @Thierry1405 can I ask you what your bachelor thesis is about?

Hey @florianrusch-zf my thesis is about building a Data Space on the basis of EDC-Connector

**Comment by florianrusch-zf** [comment]
@Thierry1405 cool, I wish you every success with your thesis

**Comment by Thierry1405** [comment]
> @Thierry1405 cool, I wish you every success with your thesis

Thank you @florianrusch-zf

**Pull request closed without merging**
