### PR TITLE
refactor: move jsonld transformers out of the dsp-transform module

### LINKED ISSUE #2781: dataspace-protocol: move `JsonLdTransformer`s out of the `dsp-transform` module
# Feature Request

Move the transformers out of the `dsp-transform` module, as they are generic and not bound to the `dsp` protocol

## Which Areas Would Be Affected?
transform

## Why Is the Feature Desired?
_Are there any requirements?_

## Solution Proposal
_If possible, provide a (brief!) solution proposal._

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Move the `JsonLdTransformer`s regarding `Policy` and `Catalog` from `dsp-transformer` to `json-ld`

## Why it does that

make these transformers available out of the `dsp` protocol (e.g. in data management)

## Further notes

- introduced a `json-ld-spi` module
- I am trying to understand why do we have different interfaces for different transformers, this will block from using these transformers in management api.
- the jsonld expansion/compaction procedure is done by two static methods that require direct module dependency, I think there should be a service registered on the runtime that can be easily injected.

## Linked Issue(s)

Closes #2781 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

**Comment by jimmarino** [comment]
+1 on introducing a service for expansion/compaction.

Which interfaces are different?

**Comment by ndr-brt** [comment]
> +1 on introducing a service for expansion/compaction.
> 
> Which interfaces are different?

`JsonLdTransformer` and `DtoTransformer`.

True is that we could inject the `JsonLdTransformerRegistry` to the `management-api` modules, but I don't get what is the advantage of keeping them separated.

**Comment by jimmarino** [comment]
> > +1 on introducing a service for expansion/compaction.
> > Which interfaces are different?
> 
> `JsonLdTransformer` and `DtoTransformer`.
> 
> True is that we could inject the `JsonLdTransformerRegistry` to the `management-api` modules, but I don't get what is the advantage of keeping them separated.

We could move everything to JsonLdTransformer and get rid of DtoTransformer. @paullatzelsperger? @juliapampus?

**Comment by jimmarino** [comment]
> > > `JsonLdTransformer` and `DtoTransformer`.
> > > True is that we could inject the `JsonLdTransformerRegistry` to the `management-api` modules, but I don't get what is the advantage of keeping them separated.
> > 
> > 
> > We could move everything to JsonLdTransformer and get rid of DtoTransformer. @paullatzelsperger? @juliapampus?
> 
> I would just keep a single registry and a single interface for transformers (JsonLd, Dto, Ids) no real advantages in have them separated.

Yes sounds good. @paullatzelsperger you will need to account for that with the type alias dispatching you are working on adding to the Json-LD transformers.

**Comment by paullatzelsperger** [comment]
> Yes sounds good. @paullatzelsperger you will need to account for that with the type alias dispatching you are working on adding to the Json-LD transformers.

I'll just put the type-alias stuff on the `TypeTransformerRegistryImpl` instead of the `JsonLdTransformerRegistryImpl`

**Comment by jimmarino** [comment]
@ndr-brt I've lost track of the state of this PR. Is it ready for review and merge or do you want to make additional changes?

**Comment by ndr-brt** [comment]
> @ndr-brt I've lost track of the state of this PR. Is it ready for review and merge or do you want to make additional changes?

it achieves the scope of the issue, other PRs will come to address the other transformer stuff, and the jsonld service as well

**Review by jimmarino — APPROVED** [review]

**Pull request merged**
