### PR TITLE
refactor(httpReceiver): rename module http-receiver to transfer-pull-http-receiver

### LINKED ISSUE #2229: Rename `http-receiver` extension
# Feature Request

The `http-receiver` is not really self-explainatory, it could be renamed to `data-plane-transfer-sync-http-edr` or something like this. Maybe it's too verbose, but I was wondering if we need that `data-plane` prefix on the `data-plane-transfer-*` extensions.

## Which Areas Would Be Affected?
extensions

## Why Is the Feature Desired?
comprehensiveness

## Solution Proposal
-

### PR DESCRIPTION
**Pull request by wolf4ood**
…

## What this PR changes/adds

Rename module `http-receiver` to `transfer-pull-http-receiver`

## Why it does that

comprehensiveness

## Further notes

While renaming I've added a test on `HttpEndpointDataReferenceReceiver`

## Linked Issue(s)

Closes #2229 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

**Comment by ndr-brt** [comment]
Since with the last PR by @bscholtes1A we better shaped the terminology for transfer types as "consumer pull" and "provider push", I'd propose to switch `sync` with `pull`, to keep an uniform terminology. wdyt?

**Review by paullatzelsperger — APPROVED** [review]

**Comment by wolf4ood** [comment]
@benjamin-fleischmann   `transfer-pull-http-receiver` ?

**Review by ndr-brt — COMMENTED** [review]
another proposal, since there's also the `transfer-data-plane`, a `transfer` folder containing both the extension could make everything tidier

**Comment by wolf4ood** [comment]
@ndr-brt  make sense, will do

**Review by bscholtes1A — APPROVED** [review]

**Pull request merged**
