### PR TITLE
fix: project url

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

updates references to the new project URL: https://github.com/orgs/eclipse-edc/projects/3

## Why it does that

Fix CI

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

**Review by mspiekermann — APPROVED** [review]

**Comment by ndr-brt** [comment]
Merging this also if the `assign-project` is broken, because its marked as `pull_request_target`, and it runs against main, will be fixed after merge

**Comment by juliapampus** [comment]
This does not work @ndr-brt I was about to change the action....

**Comment by juliapampus** [comment]
On top of that, this should not be labeled as `bug` as it has nothing to do with software bugs that should be documented like that in the changelog...

**Comment by ndr-brt** [comment]
> This does not work @ndr-brt I was about to change the action....

> On top of that, this should not be labeled as `bug` as it has nothing to do with software bugs that should be documented like that in the changelog...

whops x2: sorry :face_with_head_bandage:

**Pull request merged**
